apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenearth-local

resources:
  - ../../base

nameSuffix: -local

patches:
  - target:
      kind: Elasticsearch
      name: greenearth-es
    patch: |-
      - op: replace
        path: /spec/nodeSets/0/config/node.store.allow_mmap
        value: false
  - target:
      kind: Kibana
      name: greenearth-kibana
    patch: |-
      - op: replace
        path: /spec/elasticsearchRef/name
        value: greenearth-es-local

patchesStrategicMerge:
  - bootstrap-job-patch.yaml
  - es-service-user-setup-job-patch.yaml
