apiVersion: v1
kind: ConfigMap
metadata:
  name: hashtags-index-template
data:
  hashtags-index-template.json: |
    {
      "index_patterns": ["hashtags_v1*"],
      "template": {
        "settings": {
          "number_of_shards": $(HASHTAG_INDEX_SHARDS),
          "number_of_replicas": $(HASHTAG_INDEX_REPLICAS)
        },
        "mappings": {
          "properties": {
            "hashtag": {
              "type": "keyword",
              "index": true
            },
            "count": {
              "type": "integer",
              "index": true
            },
            "hour": {
              "type": "date",
              "format": "iso8601"
            }
          }
        }
      }
    }
