apiVersion: v1
kind: ConfigMap
metadata:
  name: likes-alias
data:
  likes-alias.json: |
    {
      "actions": [
        {
          "add": {
            "index": "likes_v1",
            "alias": "likes"
          }
        }
      ]
    }
