apiVersion: v1
kind: ConfigMap
metadata:
  name: like-tombstones-alias
data:
  like-tombstones-alias.json: |
    {
      "actions": [
        {
          "add": {
            "index": "like_tombstones_v1",
            "alias": "like_tombstones"
          }
        }
      ]
    }
