apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-alias
data:
  posts-alias.json: |
    {
      "actions": [
        {
          "add": {
            "index": "posts_v1",
            "alias": "posts"
          }
        }
      ]
    }
