apiVersion: v1
kind: ConfigMap
metadata:
  name: post-tombstones-alias
data:
  post-tombstones-alias.json: |
    {
      "actions": [
        {
          "add": {
            "index": "post_tombstones_v1",
            "alias": "post_tombstones"
          }
        }
      ]
    }
